version: '3.8'
services:
  signaling:
    image: node:20-alpine
    command: ["sh","-lc","npx -y libp2p-webrtc-star@latest --port 9090 --host 0.0.0.0"]
    networks: [web]

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - DOMAIN=signal.example.com
    networks: [web]

networks:
  web: {}
